<?php

namespace App\Http\Middleware;

use App\Exceptions\ApiGeneralException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

/**
 * Class Authenticate.
 */
class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route(home_route());
        }
    }

    protected function unauthenticated($request, array $guards) {
        if (empty($guards)) {
            $guards = [null];
        }
        foreach ($guards as $guard) {
            if ($guard == 'api') {
                throw new ApiGeneralException('Akun tidak ditemukan', 'invalid_token');
            }
        }
        parent::unauthenticated($request, $guards); // TODO: Change the autogenerated stub
    }
}
